<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE comic [
    <!ELEMENT comic (preambule, cases)>
    <!ELEMENT preambule (date, auteur+, personnages+)>
    <!ATTLIST preambule
            nombreCases CDATA #REQUIRED>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT auteur (site*, email*)>
    <!ATTLIST auteur
            prenom CDATA #REQUIRED
            nom CDATA #REQUIRED>
    <!ELEMENT site (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT personnages (personnage+)>
    <!ATTLIST personnages
            nombre CDATA #IMPLIED>
    <!ELEMENT personnage (#PCDATA)>
    <!ATTLIST personnage
            nom ID #IMPLIED
            ref IDREF #IMPLIED>
    <!ELEMENT cases (case+)>
    <!ELEMENT case (personnagesVisibles, bulles*)>
    <!ELEMENT personnagesVisibles (personnage*)>
    <!ELEMENT bulles (bulle*)>
    <!ELEMENT bulle (personnage, contenu)>
    <!ELEMENT contenu (#PCDATA)>
]>

<comic xsi:noNamespaceSchemaLocation="comic.xsd">

    <preambule nombreCases="3">
        <!-- Je n'ai pas mis la date en attibut car il peut y avoir plusieurs dates
            Date sortie, date réédition, etc...
        -->
        <date>2-16-2015</date>
        <auteur prenom="Scott" nom="Adams">
            <site>Dilbert.com</site>
            <email>DilbertCartoonist@gmail.com</email>
        </auteur>
        <personnages nombre="2">
            <personnage nom="Dilbert" />
            <personnage nom="Tina" />
        </personnages>
    </preambule>

    <cases>
        <case>
            <personnagesVisibles>
                <personnage ref="Dilbert" />
            </personnagesVisibles>
            <bulles>
                <bulle>
                    <personnage ref="Dilbert" />
                    <contenu>
                        <![CDATA[
                        YAY! I HAVE ANOTHER FULL DAY OF DOING NOTHING BUT REARRANGING ZEROS AND ONE
                        ]]>
                    </contenu>
                </bulle>
            </bulles>
        </case>
        <case>
            <personnagesVisibles>
                <personnage ref="Dilbert" />
            </personnagesVisibles>
            <bulles>
                <bulle>
                    <personnage ref="Dilbert" />
                    <contenu>
                        <![CDATA[
                        YOU KNOW IT WILL BE A GOOD DAY WHEN THERE IS NO HUMAN INTERACTION ON THE SCHEDULE
                        ]]>
                    </contenu>
                </bulle>
            </bulles>
        </case>
        <case>
            <personnagesVisibles>
                <personnage ref="Dilbert" />
                <personnage ref="Tina" />
            </personnagesVisibles>
            <bulles>
                <bulle>
                    <personnage ref="Dilbert" />
                    <contenu>
                        <![CDATA[
                        WELL, IT STARTED GOOD
                        ]]>
                    </contenu>
                </bulle>
                <bulle>
                    <personnage ref="Tina" />
                    <contenu>
                        <![CDATA[
                        HOW'S YOUR DAY GOING?
                        ]]>
                    </contenu>
                </bulle>
            </bulles>
        </case>
    </cases>
</comic>
